3-1中級　従業員一覧の並び順 sort()メソッドを使用して改修
takuyanoguchi626/ex-vue-emp-manage-bugfix pull request #10
Opened 2022-02-21 08:28 UTC by takuyanoguchi626

３－１の改修が終わりましたので、レビューお願いいたします。

問題があればコメントを頂ければと思います。
特に問題がなければマージをお願いいたします。

2022-02-21 08:39 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-21 08:39 UTC, igamasayuki commented on src/views/EmployeeList.vue
> +  /**
処理内容は正しいのですが、Vueファイルで並び替えを行うと、他に一覧画面があった際に、そこでも同じ処理を書くことになります。

他に一覧を表示させる画面があった場合でも、対応できるよう、汎用性を考えて記述する場所を変更しましょう。

2022-02-22 02:21 UTC, takuyanoguchi626 commented on src/store/index.ts
> -     * @returns 従業員一覧情報「
誤植の修正です。

2022-02-22 05:34 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-22 05:34 UTC, igamasayuki commented on src/store/index.ts
> +    },
Getterでsort()を使うと、問題なく動くのですが、デベロッパーツールでエラーが出ませんか？
「sort()はstateの配列を書き換えてしまうのですが、stateの書き換えはmutationでなければなりません。」
というようなエラーが出るはずなので、修正をお願いします。

エラーが出ない場合はslackでお知らせください。

2022-02-22 06:34 UTC, igamasayuki requested changes
気になる点をコメントしました。
差し戻しますので、再度pushして管理シートより再レビュー依頼をしてください。
(この場合、push後、再度プルリクを作る必要はありません。)

2022-02-22 06:34 UTC, igamasayuki commented on src/store/index.ts
>    }, // end mutations
画面によって、並び替えたり並び替えなかったりする場合は、このやり方でも良いのですが、わざわざ並び替えのためにmutationを呼ぶのはイマイチです。

showEmployeeListの配列を作った後に並び替えて、後のコードはそのままの方が読みやすいですし汎用性が高まります。

2022-02-22 06:38 UTC, merged